version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db

  redis:
    image: redis:7.4-alpine
    command: redis-server --requirepass redispass
    environment:
      REDIS_PASSWORD: redispass
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=redis://:redispass@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:redispass@redis:6379/0
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=redis://:redispass@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:redispass@redis:6379/0
    depends_on:
      - redis
      - db

volumes:
  pg_data:
